done
uwumarogie/ITBL-TEST pull request #2
Opened 2024-04-19 14:41 UTC by walamana

2024-04-19 14:56 UTC, uwumarogie requested changes

2024-04-19 14:56 UTC, uwumarogie commented on src/app/about/page.tsx
> +"use client"
page.tsx file are most of the server components. meaning you don't need the "use client"

2024-04-19 14:56 UTC, uwumarogie commented on src/app/layout.tsx
> +        </div>
noice idea. just place it in a separate function

2024-04-19 14:56 UTC, uwumarogie commented on src/app/search/layout.tsx
> +export default function SearchLayout({children}) {
({children}: {children: React.ReactNode})

2024-04-19 14:56 UTC, uwumarogie commented on src/app/search/layout.tsx
> +"use client"
why do you need here a "use client"? It's correct. But why

2024-04-19 14:56 UTC, uwumarogie commented on src/app/search/results/page.tsx
> +        </div>
search for the workflow of server component to client component. Tipp: how don't need the useEffect :)

2024-04-19 14:56 UTC, uwumarogie commented on src/app/search/results/page.tsx
> +    return <div>
please add some ()

2024-04-19 16:46 UTC, walamana commented on src/app/search/layout.tsx
> +"use client"
Don't have the code on hand but I think there is a request that uses client api. I could possibly do it with some sort of server request. But I was to lazy to look that up right now 😅

2024-04-19 16:49 UTC, walamana commented on src/app/search/layout.tsx
> +"use client"
Oh nice, I just looked it up and saw that fetch is also available server side. I'll have a look at it some time :)

2024-04-20 20:54 UTC, uwumarogie commented on src/app/search/layout.tsx
> +"use client"
Everytime you have interactivity in the component e.g. by clicking a button when you use useState you have to use "use client". 

workflow: server to client component

2024-09-06 10:11 UTC, closed without merging